FROM ghcr.io/camptocamp/azure-debug-helper:common

COPY banner /root/banner

# Use bash to build image for dynamic variables substitution
SHELL ["/bin/bash", "-c"]

# Install keys for external repository
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
   --mount=target=/var/cache/apt,type=cache,sharing=locked \
    apt-get update && \
    apt-get install -y redis-tools && \
RUN echo "cat /root/banner" >> /root/.bashrc
