FROM debian:trixie

ARG TOOLS="git curl ca-certificates gnupg apt-transport-https rsync vim-nox emacs-nox screen wget file nano htop sudo tree less bash-completion zsh figlet colordiff unzip tmux" \
    PGDG_KEY="https://www.postgresql.org/media/keys/ACCC4CF8.asc" \
    PGDG_PACKAGE="postgresql-client-12 postgresql-client-13 postgresql-client-14 postgresql-client-15 postgresql-client-16 postgresql-client-17 postgresql-client-18 libpq-dev pgtop" \
    AZURE_KEY="https://packages.microsoft.com/keys/microsoft.asc" \
    AZURE_PACKAGE="azure-cli"

# Use bash to build image for dynamic variables substitution
SHELL ["/bin/bash", "-c"]

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
   --mount=target=/var/cache/apt,type=cache,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends ${TOOLS}

# Install keys for external repository
ADD --chmod=644 "$PGDG_KEY" "/etc/apt/keyrings/pgdg.asc"
ADD --chmod=644 "$AZURE_KEY" "/etc/apt/keyrings/microsoft.asc"
COPY repos/*.sources /etc/apt/sources.list.d/

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
   --mount=target=/var/cache/apt,type=cache,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends ${AZURE_PACKAGE} ${PGDG_PACKAGE}
