FROM ghcr.io/camptocamp/azure-debug-helper:common

COPY banner ~/banner

# Use bash to build image for dynamic variables substitution
SHELL ["/bin/bash", "-c"]

# Install keys for external repository
RUN apt-get update && \
    apt-get install -y redis-tools && \
    apt-get clean && \
    rm -rf /var/apt/lists/*
RUN echo "cat ~/banner" >> ~/.bashrc
